#release configuration
#Wed Jun 18 12:46:34 CEST 2025
completedPhase=check-poms
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.scm.local.jarios\:version_helper.connection=scm\:git\:git@github.com\:contratacionmalaga/version_helper.git
project.scm.local.jarios\:version_helper.developerConnection=scm\:git\:git@github.com\:contratacionmalaga/version_helper.git
project.scm.local.jarios\:version_helper.tag=HEAD
project.scm.local.jarios\:version_helper.url=https\://github.com/contratacionmalaga/version_helper.git
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[RELEASE]
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tagNameFormat=v@{project.version}
scm.url=scm\:git\:git@github.com\:contratacionmalaga/version_helper.git
